[package]
name = "bulk-jxl"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
walkdir = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
human_bytes = "0.4"
inquire = "0.7"
filetime = "0.2"